#!/command/with-contenv bash
exec s6-setuidgid www-data redis-server \
    --bind 127.0.0.1 \
    --port 6379 \
    --dir /config/redis \
    --appendonly yes \
    --appendfsync everysec \
    --daemonize no \
    --logfile ""
