#!/command/with-contenv bash
if [ ! -d /config/mariadb/mysql ]; then
    echo "Initialising MariaDB data directory"
    mariadb-install-db --user=www-data --datadir=/config/mariadb --skip-test-db >/dev/null
fi
exec s6-setuidgid www-data mariadbd \
    --user=www-data \
    --datadir=/config/mariadb \
    --socket=/run/mysqld/mysqld.sock \
    --bind-address=127.0.0.1 \
    --skip-name-resolve \
    --max_allowed_packet=128M \
    --group_concat_max_len=16384 \
    --max_connections=200 \
    --innodb_log_file_size=1G \
    --innodb_flush_log_at_trx_commit=2 \
    --transaction-isolation=READ-COMMITTED \
    --tmp_table_size=256M \
    --max_heap_table_size=256M \
    --innodb_buffer_pool_size="${DB_INNODB_BUFFER_POOL_SIZE:-1G}"
