searchd
{
	listen			= 127.0.0.1:9306:mysql
	listen			= 127.0.0.1:9308:http
	data_dir		= /config/manticore/data
	log			= /config/manticore/searchd.log
	pid_file		= /config/manticore/searchd.pid
	network_timeout		= 5
	client_timeout		= 300
	seamless_rotate		= 1
	preopen_tables		= 1
	unlink_old		= 1
	max_packet_size		= 16M
	max_open_files		= 65535
	binlog_flush		= 2
	binlog_max_log_size	= 512M
	rt_flush_period		= 900
	expansion_limit		= 1000
	secondary_indexes	= 1
	pseudo_sharding		= 1
}
